[2020-04-18 03:08:59,374][Thread-6:123145394393088][task_id:django.security.csrf][log.py:228][WARNING][Forbidden (CSRF cookie not set.): /backend/add_article/upload_img/]
[2020-04-18 03:09:30,604][Thread-6:123145394393088][task_id:django.security.csrf][log.py:228][WARNING][Forbidden (CSRF cookie not set.): /backend/add_article/upload_img/]
[2020-04-18 03:09:30,676][Thread-6:123145394393088][task_id:django.security.csrf][log.py:228][WARNING][Forbidden (CSRF cookie not set.): /backend/add_article/upload_img/]
[2020-04-18 03:13:15,021][Thread-10:123145404903424][task_id:django.request][log.py:228][ERROR][Internal Server Error: /backend/add_article/upload_img/]
Traceback (most recent call last):
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/deyoukong/BBS_Blog/backend/views.py", line 38, in add_article
    soup = BeautifulSoup(article_con, 'html.parser')
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/bs4/__init__.py", line 287, in __init__
    elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()
[2020-04-18 04:33:43,830][Thread-6:123145546047488][task_id:django.request][log.py:228][ERROR][Internal Server Error: /blog/up_down/]
Traceback (most recent call last):
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/deyoukong/BBS_Blog/blog/views.py", line 293, in up_down
    return JsonResponse(res)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ArticleUpDown' is not JSON serializable
[2020-04-18 04:33:55,490][Thread-8:123145551302656][task_id:django.request][log.py:228][ERROR][Internal Server Error: /blog/up_down/]
Traceback (most recent call last):
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/deyoukong/BBS_Blog/blog/views.py", line 293, in up_down
    return JsonResponse(res)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ArticleUpDown' is not JSON serializable
[2020-04-18 04:34:37,654][Thread-8:123145551302656][task_id:django.request][log.py:228][ERROR][Internal Server Error: /blog/up_down/]
Traceback (most recent call last):
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/deyoukong/BBS_Blog/blog/views.py", line 293, in up_down
    return JsonResponse(res)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ArticleUpDown' is not JSON serializable
[2020-04-18 04:35:00,426][Thread-8:123145551302656][task_id:django.request][log.py:228][ERROR][Internal Server Error: /blog/up_down/]
Traceback (most recent call last):
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/deyoukong/BBS_Blog/blog/views.py", line 293, in up_down
    return JsonResponse(res)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ArticleUpDown' is not JSON serializable
[2020-04-18 04:38:12,565][Thread-7:123145512738816][task_id:django.request][log.py:228][ERROR][Internal Server Error: /blog/up_down/]
Traceback (most recent call last):
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/deyoukong/BBS_Blog/blog/views.py", line 293, in up_down
    return JsonResponse(res)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ArticleUpDown' is not JSON serializable
[2020-04-18 04:47:39,822][Thread-7:123145426849792][task_id:django.request][log.py:228][ERROR][Internal Server Error: /blog/up_down/]
Traceback (most recent call last):
  File "/Users/deyoukong/BBS_Blog/blog/views.py", line 286, in up_down
    models.Article.objects.filter(pk=article_id).update(up_count=F("ip_count") + 1)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/db/models/query.py", line 689, in update
    query.add_update_values(kwargs)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/db/models/sql/subqueries.py", line 129, in add_update_values
    return self.add_update_fields(values_seq)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/db/models/sql/subqueries.py", line 140, in add_update_fields
    val = val.resolve_expression(self, allow_joins=False, for_save=True)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/db/models/expressions.py", line 445, in resolve_expression
    c.lhs = c.lhs.resolve_expression(query, allow_joins, reuse, summarize, for_save)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/db/models/expressions.py", line 509, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1570, in resolve_ref
    join_info = self.setup_joins(field_list, self.get_meta(), self.get_initial_alias(), can_reuse=reuse)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1473, in setup_joins
    names[:pivot], opts, allow_many, fail_on_missing=True,
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1389, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'ip_count' into field. Choices are: article2tag, articledetail, articleupdown, category, category_id, comment, comment_count, create_time, desc, down_count, nid, tags, title, up_count, user, user_id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/deyoukong/BBS_Blog/blog/views.py", line 291, in up_down
    res["first_operate"] = models.ArticleUpDown.objects.filter(article_id=article_id, user_id=user_id).first().is_up
AttributeError: 'NoneType' object has no attribute 'is_up'
[2020-04-18 04:57:10,430][Thread-1:123145438916608][task_id:django.request][log.py:228][ERROR][Internal Server Error: /blog/up_down/]
Traceback (most recent call last):
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/deyoukong/BBS_Blog/blog/views.py", line 278, in up_down
    collect_logger.info("点赞/踩灭：文章id" + article_id + "   点赞True/踩False：" +is_up + "   用户id" + user_id)
TypeError: must be str, not bool
[2020-04-18 04:57:59,605][Thread-1:123145317081088][task_id:django.request][log.py:228][ERROR][Internal Server Error: /blog/up_down/]
Traceback (most recent call last):
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/deyoukong/BBS_Blog/blog/views.py", line 278, in up_down
    collect_logger.info("点赞/踩灭：文章id" + article_id + "   点赞True/踩False：" + str(is_up) + "   用户id" + user_id)
TypeError: must be str, not int
[2020-04-18 04:59:10,670][Thread-5:123145521192960][task_id:collect][views.py:278][INFO][点赞/踩灭：文章id8   点赞True/踩False：True   用户id13]
[2020-04-18 04:59:57,254][Thread-5:123145521192960][task_id:collect][views.py:278][INFO][点赞/踩灭：文章id8   点赞True/踩False：False   用户id13]
[2020-04-18 04:59:57,257][Thread-5:123145521192960][task_id:collect][views.py:291][INFO][点赞/踩灭异常：文章id:8，点赞True/踩False：False，用户id：13，异常信息：UNIQUE constraint failed: blog_articleupdown.article_id, blog_articleupdown.user_id]
[2020-04-18 05:37:56,863][Thread-4:123145533784064][task_id:collect][views.py:307][INFO][评论：文章id：8，评论内容：hahahah，用户id：13，父评论id：]
[2020-04-18 05:42:11,634][Thread-4:123145460510720][task_id:collect][views.py:306][INFO][评论：文章id：8，评论内容：测试一下，用户id：13，父评论id：]
[2020-04-18 05:47:26,002][Thread-1:123145440747520][task_id:collect][views.py:306][INFO][评论：文章id：8，评论内容：测试一下最新的评论，用户id：13，父评论id：]
[2020-04-18 06:02:08,986][Thread-4:123145440747520][task_id:django.request][log.py:228][ERROR][Internal Server Error: /blog/Sampson/article/8/]
Traceback (most recent call last):
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/deyoukong/BBS_Blog/blog/views.py", line 262, in article_detail
    "blog": blog,
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':'Y-m-d H:i\'' from 'comment.create_time|date:'Y-m-d H:i\''
[2020-04-18 06:02:58,527][Thread-4:123145440747520][task_id:django.request][log.py:228][ERROR][Internal Server Error: /blog/Sampson/article/8/]
Traceback (most recent call last):
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/deyoukong/BBS_Blog/blog/views.py", line 262, in article_detail
    "blog": blog,
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':'%Y-%m-%d %H:%i\'' from 'comment.create_time|date:'%Y-%m-%d %H:%i\''
[2020-04-18 06:02:59,175][Thread-4:123145440747520][task_id:django.request][log.py:228][ERROR][Internal Server Error: /blog/Sampson/article/8/]
Traceback (most recent call last):
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/deyoukong/BBS_Blog/blog/views.py", line 262, in article_detail
    "blog": blog,
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':'%Y-%m-%d %H:%i\'' from 'comment.create_time|date:'%Y-%m-%d %H:%i\''
[2020-04-18 06:02:59,543][Thread-4:123145440747520][task_id:django.request][log.py:228][ERROR][Internal Server Error: /blog/Sampson/article/8/]
Traceback (most recent call last):
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/deyoukong/BBS_Blog/blog/views.py", line 262, in article_detail
    "blog": blog,
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':'%Y-%m-%d %H:%i\'' from 'comment.create_time|date:'%Y-%m-%d %H:%i\''
[2020-04-18 06:02:59,776][Thread-4:123145440747520][task_id:django.request][log.py:228][ERROR][Internal Server Error: /blog/Sampson/article/8/]
Traceback (most recent call last):
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/deyoukong/BBS_Blog/blog/views.py", line 262, in article_detail
    "blog": blog,
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':'%Y-%m-%d %H:%i\'' from 'comment.create_time|date:'%Y-%m-%d %H:%i\''
[2020-04-18 06:03:00,018][Thread-4:123145440747520][task_id:django.request][log.py:228][ERROR][Internal Server Error: /blog/Sampson/article/8/]
Traceback (most recent call last):
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/deyoukong/BBS_Blog/blog/views.py", line 262, in article_detail
    "blog": blog,
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':'%Y-%m-%d %H:%i\'' from 'comment.create_time|date:'%Y-%m-%d %H:%i\''
[2020-04-18 06:03:00,383][Thread-4:123145440747520][task_id:django.request][log.py:228][ERROR][Internal Server Error: /blog/Sampson/article/8/]
Traceback (most recent call last):
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/deyoukong/BBS_Blog/blog/views.py", line 262, in article_detail
    "blog": blog,
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':'%Y-%m-%d %H:%i\'' from 'comment.create_time|date:'%Y-%m-%d %H:%i\''
[2020-04-18 06:03:00,689][Thread-4:123145440747520][task_id:django.request][log.py:228][ERROR][Internal Server Error: /blog/Sampson/article/8/]
Traceback (most recent call last):
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/deyoukong/BBS_Blog/blog/views.py", line 262, in article_detail
    "blog": blog,
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':'%Y-%m-%d %H:%i\'' from 'comment.create_time|date:'%Y-%m-%d %H:%i\''
[2020-04-18 06:08:15,518][Thread-23:123145440747520][task_id:django.request][log.py:228][ERROR][Internal Server Error: /blog/Sampson/article/1/]
Traceback (most recent call last):
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/deyoukong/BBS_Blog/blog/views.py", line 262, in article_detail
    "blog": blog,
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/Users/deyoukong/BBS_Blog/venv/lib/python3.6/site-packages/django/template/base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':\'Y-m-d H:i\'' from 'comment.create_time|date:\'Y-m-d H:i\''
[2020-04-18 06:25:19,712][Thread-39:123145446002688][task_id:collect][views.py:306][INFO][评论：文章id：1，评论内容：我在测试一下，用户id：13，父评论id：]
[2020-04-18 06:27:43,259][Thread-4:123145394180096][task_id:collect][views.py:306][INFO][评论：文章id：1，评论内容：崽子啊，用户id：13，父评论id：]
[2020-04-18 06:30:17,871][Thread-5:123145399435264][task_id:collect][views.py:306][INFO][评论：文章id：1，评论内容：hahahah，用户id：13，父评论id：]
